# 1.- Crear una matriz 3x3 con valores de 0 a 8

In [1]:
import numpy as np

valores = np.arange(0,9)

In [2]:
valores

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [7]:
matriz = np.reshape(valores, (3,3) )

In [8]:
matriz

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

# 2.- Crear una matriz identidad de 6x6

In [9]:
matriz2 = np.identity(6)

In [10]:
matriz2

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])