## 1.- Crea un vector con valores dentro del rango 3 a el número que  representa tu edad.

In [2]:
import numpy as np

rangoEdad = np.array(range(3,36))

rangoEdad


array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
       20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35])

## 2.- Crea un arreglo con los siguientes elementos:[0, 1, 2, 3, 4, 0, 1, 2, 3, 4]

In [3]:
arrayElems = np.array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4])

arrayElems

array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4])

## 3.- Ordena de forma ascendiente dicho arreglo.

In [4]:
arrayElems.sort()

arrayElems

array([0, 0, 1, 1, 2, 2, 3, 3, 4, 4])